language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
before_script:
  - yarn
script:
  - yarn build
  - yarn bundle
deploy:
  - provider: surge
    project: ./
    domain: vue-chat-autosize-typebox.surge.sh
    skip-cleanup: true
    on:
      branch: master
  - provider: npm
    email: ${EMAIL}
    api_key: ${AUTH_TOKEN}
    skip_cleanup: true
    on:
      branch: master